
server:
  port: 9090

spring:
  application:
    name: UserServices
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pass123
    url: jdbc:mysql://localhost:3306/Microservies
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
